# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ccb2cf9720c98cc2a53082b5b68e843ff23094e117f30c33e01af9e55e30a8efaa9625bebc0295c00921c3906c4eb11d058060b3f761318e4129d814e3a10b8

test:
  secret_key_base: e92e926ef530544b59b8c9857956113817bf2eff39bf8f5076f29f57d08d47861651fb4be3a524caae59f82bf4f31221960756278471e14d2f0eebd1648cfea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
